name: Release

on:
  push:
    branches: [main, master]  # Triggers on both common default branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install
        run: npm install --legacy-peer-deps
        
      - name: Build
        run: npm run build